### ISSUE TITLE
compiling gps-sdr-sim-realtime using usrp X310

### ISSUE THREAD

**Issue by bikilay** [gym487/gps-sdr-sim-realtime#1]
when i try to compile with  "$ gcc gpssim.c -lm -O3 -o gps-sdr-sim" compiler  on ubuntu using usrp X310, the following error generated.....the error is pointing in to  "socket.c" which is about connecting to TCP.......

$ gcc gpssim.c -lm -O3 -o gps-sdr-sim
In file included from gpssim.c:14:0:
socket.c: In function ‘timem’:
socket.c:41:2: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  gettimeofday(&t, NULL);
  ^~~~~~~~~~~~
socket.c: In function ‘udprecv’:
socket.c:60:41: warning: passing argument 6 of ‘recvfrom’ makes pointer from integer without a cast [-Wint-conversion]
  return recvfrom(s, dataa, siz, 0,&from,sizeof(from));
                                         ^~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:269:0,
                 from socket.c:2,
                 from gpssim.c:14:
/usr/include/x86_64-linux-gnu/bits/socket2.h:64:1: note: expected ‘socklen_t * restrict {aka unsigned int * restrict}’ but argument is of type ‘long unsigned int’
 recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags,
 ^~~~~~~~
In file included from gpssim.c:14:0:
socket.c: At top level:
socket.c:63:30: warning: excess elements in array initializer
 double llhr[3]={39.68,139,76,10};
                              ^~
socket.c:63:30: note: (near initialization for ‘llhr’)
gpssim.c: In function ‘usage’:
gpssim.c:1651:9: warning: format ‘%f’ expects argument of type ‘double’, but argument 2 has type ‘char *’ [-Wformat=]
  printf("Usage: gps-sdr-sim [options]\n"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gpssim.c:1665:3:
   "  -n <port>        Use TCP connect to Gnuradio TCP-Source for\n realtime simulation.\n",
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by gym487** [comment]
There are some warnings needs to be fixed. But it could still be compiled and generate a functional binary file now while ignoring that.

**Comment by gym487** [comment]
Fixed.
