### ISSUE TITLE
GPS signal does not work

### ISSUE THREAD

**Issue by Antanide** [gym487/gps-sdr-sim-realtime#2]
I am using hackrf.
With the original gps-sdr-sim I can successfully transmit GPS signals that are detected by test units. So the hardware looks OK.

With this project I can connect to gnuradio and show the waterfall and frequency graph:
![image](https://user-images.githubusercontent.com/22542920/67893626-31ef3e80-fb57-11e9-8257-225a41d64e64.png)

But no signal gets detected by the GPS units.
If I can help debugging in any way please just tell me.
Thanks,

**Comment by Antanide** [comment]
Nevermind, I got it working. I just had to tune the amplifier.

BTW I expected this to generate a realtime signal, while the time sent is the one of the ephemeris file.

**Comment by shinedlc** [comment]
> ind, I got it working. I just had

same problem，how to  tune the amplifier ？？

**Comment by shinedlc** [comment]
finally it works, change  gpssim.c file: float * to char *, and change tcp.grc TCP Source Output Type: byte, then link to IChar To Complex:

```
		if(usesocket==true){
			//float *datap=(float*)calloc(iq_buff_size*2,sizeof(float));
			signed char *datap=(signed char *)calloc(iq_buff_size*2,sizeof(signed char));
			int l=0;
			for(l=0;l<iq_buff_size*2;l++){
				datap[l]= iq_buff[l] >> 4;
			}
			socksend(sockc,datap,iq_buff_size*2*sizeof(signed char));
			free(datap);
		}
```
