### ISSUE TITLE
Dependency information is missing 依赖库信息缺失

### ISSUE THREAD

**Issue by Chapoly1305** [gym487/gps-sdr-sim-realtime#3]
The mapper.py is written in python2, which requires module "web".
Use the following commands to install this module.

mapper.py 使用了Python2的模块"web"，这个需要使用如下命令额外安装。
```
sudo apt install python-pip
pip install web.py==0.40
```

Ref:
https://webpy.org/install

**Comment by gym487** [comment]
Upgraded to Python3.
#6
