### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by retalieight** [gym487/gps-sdr-sim-realtime#5]
[chown@mbp ~/Downloads/gps-sdr-sim-realtime (master *)]$ bladeRF-cli -s bladerf.script

For best results, it is not recommended to set both RX and TX to the
same frequency. Instead, consider offsetting them by at least 1 MHz
and mixing digitally.

For the above reason, 'set frequency <value>` is deprecated and
scheduled for removal in future bladeRF-cli versions.

Please use 'set frequency rx' and 'set frequency tx' to configure
channels individually.

  RX1 Frequency: 1575419998 Hz (Range: [70000000, 6000000000])
  RX2 Frequency: 1575419998 Hz (Range: [70000000, 6000000000])
  TX1 Frequency: 1575419998 Hz (Range: [47000000, 6000000000])
  TX2 Frequency: 1575419998 Hz (Range: [47000000, 6000000000])

  Setting RX1 sample rate - req:   2600000 0/1Hz, actual:   2600000 0/1Hz
  Setting RX2 sample rate - req:   2600000 0/1Hz, actual:   2600000 0/1Hz
  Setting TX1 sample rate - req:   2600000 0/1Hz, actual:   2600000 0/1Hz
  Setting TX2 sample rate - req:   2600000 0/1Hz, actual:   2600000 0/1Hz

  RX1 Bandwidth:   2500000 Hz (Range: [200000, 56000000])
  RX2 Bandwidth:   2500000 Hz (Range: [200000, 56000000])
  TX1 Bandwidth:   2500000 Hz (Range: [200000, 56000000])
  TX2 Bandwidth:   2500000 Hz (Range: [200000, 56000000])

  Error (bladerf.script:3): Invalid operation or parameter

**Comment by gym487** [comment]
It might be fixed in #8  https://github.com/gym487/gps-sdr-sim-realtime/pull/8/commits/03db365cb7b9ea1e5122e7212bbf938ee1973c0f
