### ISSUE TITLE
GNU Radio Missing Block (tcp source)

### ISSUE THREAD

**Issue by lenhart** [gym487/gps-sdr-sim-realtime#7]
Hi, 
thank you for your work on the real-time version of the gps-sdr-sim library!

I am trying to get the gnu radio part running, but ran into a problem there The source is marked as 'missing block' for me. Is there some kind of libraries required to run it? (3rd party sdr lib for instance..)

Updating gnuradio to 3.9 did not help, but now I can say that it is not one of the newer tcp server/client nodes..

Thanks!

**Comment by lenhart** [comment]
Ah, I think I found my mistake.. there is some python block in the top level folder. I'll try to import that and see how it works! (will either close this issue or comment again)

**Comment by lenhart** [comment]
first, I am new to gnuradio, so I am still not totally sure how things work together here. The top_block.py seems to be auto generated from tcp.grc, thus not solving the problem of the unknown block.

[This](https://github.com/gnuradio/gnuradio/issues/1540) issue seems to be related. blks2 tcp source is deprecated due to certain issues. Assuming gnu radio 3.9 it should be possible to replace it with the [tcp server sink](https://wiki.gnuradio.org/index.php/TCP_Server_Sink), right? 
Currently I have an issue building the flow, though but I'll try again tomorrow

**Comment by lenhart** [comment]
as an update: grc 3.9 seems not to be fully usable as of now, so I did not make any progress there. 
Trying to let grc use an old python version with deprecated blocks seems unsatisfying as well..
Not sure hat the best thing to do would be here..

**Comment by smartboytao** [comment]
uninstall gnuradio 3.8(or 3.9), install gnuradio 3.7

**Comment by gym487** [comment]
It seems that the TCP source was come back in grc 3.10.
